### ISSUE TITLE
How to get cheek points?

### ISSUE THREAD

**Issue by dhesru** [hriddhidey/visage#4]
I am working on this script and unsure on how to get the coordinates for the cheeks? 
I used to get the ROI of cheeks, but it is a rectangle. From there im unable to get the pixel coordinates of the ROI.
If you have any better alternatives, do let me know.

**Comment by lupangsogood** [comment]
you need to get number of point from 68 predict and make it like BOUND 
example 
![image](https://user-images.githubusercontent.com/10386575/53904882-b09fe480-4079-11e9-8336-bd83958d0485.png)
