### ISSUE TITLE
Add gloss, matte effects

### ISSUE THREAD

**Issue by dhesru** [hriddhidey/visage#5]
Any one know how to achieve gloss effect on lips?

**Comment by Siddharthm10** [comment]
Did you achieve this? Or do you have any hint on how to proceed with this?
@sur22end @hriddhidey

**Comment by dhesru** [comment]
Nope. The plan was dropped. Maybe this could be achieved in the front-end. Just a thought.

**Comment by Siddharthm10** [comment]
Okay thanks :). I'll check it out
